### ISSUE TITLE
Can I use for other languages like english or chinese?

### ISSUE THREAD

**Issue by wyt1234** [gteu/realtime-ppg-vc#1]

**Comment by gteu** [comment]
Hi @wyt1234.

I'm sorry. Only Japanese is supported currently.
But the same model will work for other languages.
What you need to do is to prepare speech and corresponding phoneme sequences to train ASR model.

Example:
Input: 40-dim Mel-spectrogram per frame (For input, the same code can be used.)
Output: 1-dim phoneme per frame (For output, you need to process by yourself using alignment tools for another language.)

**Comment by leospark** [comment]
> _No description provided._

May I ask if you train the ppg-vc model for Chinese tasks?  @wyt1234
